main: life.savag3.InventoryCommand.Main
version: 2.0
name: InventoryCommand
api-version: 1.14
author: Savag3life
depend: [PlaceholderAPI]
softdepend: [DeluxeChat]
commands:
  seeinv:
    description: See Players Inventory.
  invreload:
    description: Reload plugin config.